[package]
name = "spinlock"
description = "A no_std Spinlock implementation."
repository = "https://github.com/trayzen/spinlock"
version = "0.0.1"
authors = ["TrAyZeN"]
edition = "2018"
license = "MIT"
keywords = [
    "lock",
    "no-std",
]
categories = [
    "no-std",
]
