[package]
name = "spinlock"
description = "no_std synchronization primitives using spinlock."
repository = "https://github.com/trayzen/spinlock"
version = "0.0.1"
authors = ["TrAyZeN"]
edition = "2021"
license = "MIT"
keywords = [
    "lock",
    "no-std",
]
categories = [
    "no-std",
]
